### ISSUE TITLE
Double close of DoneCh in rpc_server

### ISSUE THREAD

**Issue by dadgar** [hashicorp/go-plugin#22]
```
2017/02/13 22:38:36 [DEBUG] plugin: nomad: panic: close of closed channel
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 
2017/02/13 22:38:36 [DEBUG] plugin: nomad: goroutine 81 [running]:
2017/02/13 22:38:36 [DEBUG] plugin: nomad: panic(0x107ae00, 0xc4202b09d0)
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
2017/02/13 22:38:36 [DEBUG] plugin: nomad: github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-plugin.(*controlServer).Quit(0xc42008e588, 0x1, 0x1a27ec8, 0x0, 0x0)
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/gopath/src/github.com/hashicorp/nomad/vendor/github.com/hashicorp/go-plugin/rpc_server.go:118 +0x5a
2017/02/13 22:38:36 [DEBUG] plugin: nomad: reflect.Value.call(0xc420020960, 0xc42008e590, 0x13, 0x11f9fcb, 0x4, 0xc420466ef0, 0x3, 0x3, 0xc420260601, 0xc4202606a0, ...)
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:434 +0x5c8
2017/02/13 22:38:36 [DEBUG] plugin: nomad: reflect.Value.Call(0xc420020960, 0xc42008e590, 0x13, 0xc420466ef0, 0x3, 0x3, 0x1, 0xc4202e6780, 0x20003)
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:302 +0xa4
2017/02/13 22:38:36 [DEBUG] plugin: nomad: net/rpc.(*service).call(0xc420211740, 0xc420211700, 0xc42034aab0, 0xc420098800, 0xc420355760, 0xff8160, 0xc4202b0987, 0x181, 0xfe42e0, 0x1a27ec8, ...)
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/.gimme/versions/go1.7.linux.amd64/src/net/rpc/server.go:383 +0x148
2017/02/13 22:38:36 [DEBUG] plugin: nomad: created by net/rpc.(*Server).ServeCodec
2017/02/13 22:38:36 [DEBUG] plugin: nomad: 	/home/travis/.gimme/versions/go1.7.linux.amd64/src/net/rpc/server.go:477 +0x421
2017/02/13 22:38:36 [DEBUG] plugin: /tmp/nomad-test.UjY/nomad: plugin process exited
```

Unfortunately do not have reproduction steps or full stack trace as I saw this in travis.

**Comment by mitchellh** [comment]
Fixed
