### ISSUE TITLE
Unable to get go-plugin/GRPC flavor working in container.

### ISSUE THREAD

**Issue by manther** [hashicorp/go-plugin#45]
Problem first happened with my teams project, but recreated the issue using the go-plugins example to be sure. 

Steps:

Container built FROM golang:latest

run interactively 

    1  go get github.com/hashicorp/go-plugin
    2  cd src/github.com/hashicorp/go-plugin/examples/grpc/
    3  go build -o kv
    4  go build -o kv-go-grpc ./plugin-go-grpc
    5  export KV_PLUGIN="./kv-go-grpc"
    6  ./kv put hello world

root@b93305f57ca2:/go/src/github.com/hashicorp/go-plugin/examples/grpc# ./kv put hello world
2017-10-02T22:51:35.213Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c ./kv-go-grpc]"
2017-10-02T22:51:35.214Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2017-10-02T22:51:35.220Z [DEBUG] plugin.sh: plugin address: timestamp=2017-10-02T22:51:35.220Z address=/tmp/plugin040334221 network=unix

*It just hangs here indefinitely. (Same behavior as in my current project). 

If, I do the same for the basic example and it runs fine. 

Thanks!

**Comment by mitchellh** [comment]
Hm, is it possible that Unix domain sockets aren't allowed or working correctly? Or something to do with the `/tmp` directory perhaps? I wonder if you force TCP it works...

I'll take a look at this. Thanks!

**Comment by manther** [comment]
NP. Where would I got to try and force TCP?

**Comment by manther** [comment]
Got a product i'm getting close to launching that I was hoping to use this functionality in containers. Any idea where this bug sits in terms of roadmap?

**Comment by manther** [comment]
A little more information, maybe this will help:
We can see the communication between server and client is happening, but when the server piece is supposed to exit it doesn't. You can see that the actual KV put worked, after we exit the process. As well you can see the get works too, but again you have to exit the process. Also in each case the socket file gets created.

```
root@7c3bf8270953:/automation/alt_plugins# ./kv put bar biz
2017-10-31T16:26:10.560Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c ./kv-go-grpc]"
2017-10-31T16:26:10.561Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2017-10-31T16:26:10.605Z [DEBUG] plugin.sh: plugin address: timestamp=2017-10-31T16:26:10.605Z address=/tmp/plugin795473381 network=unix
^C
root@7c3bf8270953:/automation/alt_plugins# ls -k kv_bar
kv_bar
root@7c3bf8270953:/automation/alt_plugins# cat kv_bar
biz

Written from plugin-go-grpcroot@7c3bf8270953:/automation/alt_plugins# ./kv get bar
2017-10-31T16:26:24.309Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c ./kv-go-grpc]"
2017-10-31T16:26:24.311Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2017-10-31T16:26:24.355Z [DEBUG] plugin.sh: plugin address: timestamp=2017-10-31T16:26:24.355Z address=/tmp/plugin262545223 network=unix
biz

Written from plugin-go-grpc
^C
root@7c3bf8270953:/automation/alt_plugins# ls -l /tmp/plugin262545223
srwxr-xr-x 1 root root 0 Oct 31 16:26 /tmp/plugin262545223```

**Comment by manther** [comment]
Also, the kv-go-grpc processes are still running after exiting the kv client process.

```
root@7c3bf8270953:~# ps -ef |grep grpc
root       165     0  0 16:25 ?        00:00:00 ./kv-go-grpc
root       181     0  0 16:25 ?        00:00:00 sh -c ./kv-go-grpc
root       184   181  0 16:25 ?        00:00:00 ./kv-go-grpc
root       198     0  0 16:25 ?        00:00:00 ./kv-go-grpc
root       236     0  0 16:26 ?        00:00:00 sh -c ./kv-go-grpc
root       239   236  0 16:26 ?        00:00:00 ./kv-go-grpc
root       275     0  0 16:26 ?        00:00:00 ./kv-go-grpc ```

**Comment by aantono** [comment]
I've ran into the same problem as well, and it seems that commenting out this line https://github.com/hashicorp/go-plugin/blob/master/client.go#L391 `<-doneCh` seems to fix the problem (I had a unit test that would just block when running inside the container forever, and with that line commented out, it succeeds and things exit)

**Comment by aantono** [comment]
@mitchellh, I just also tried forcing the TCP protocol instead of Unix Socket, but the problem still persisted...  just FYI.

```2017-11-06T18:45:37.757Z [DEBUG] plugin: starting plugin: path=/bin/sh args="[sh -c /go/src/github.com/containous/traefik/plugin/test/plugin-test-go-grpc_linux-amd64]"
2017-11-06T18:45:37.758Z [DEBUG] plugin: waiting for RPC address: path=/bin/sh
2017-11-06T18:45:37.768Z [DEBUG] plugin.sh: plugin address: timestamp=2017-11-06T18:45:37.767Z address=127.0.0.1:10001 network=tcp
2017-11-06T18:45:37.768Z [DEBUG] plugin.sh: Processing plugin request: from within plugin...: timestamp=2017-11-06T18:45:37.768Z
SIGQUIT: quit
PC=0x71ed91 m=0 sigcode=0
```

Just like in @manther case, the plugin process still runs after the client process is killed.

**Comment by aantono** [comment]
@mitchellh any possible updates on the topic?

**Comment by aantono** [comment]
Here is a complete stack dump after the timeout crash:
```
SIGQUIT: quit
PC=0x71ee51 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x115de90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffdd24f96d8, 0x6d024b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:438 +0x21
runtime.futexsleep(0x115de90, 0x7ffd00000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x115de90)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1680 +0xe5
runtime.findrunnable(0xc42001e600, 0x0)
	/usr/local/go/src/runtime/proc.go:2135 +0x4d2
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2255 +0x12c
runtime.park_m(0xc42034c180)
	/usr/local/go/src/runtime/proc.go:2318 +0xb6
runtime.mcall(0x7ffdd24f9870)
	/usr/local/go/src/runtime/asm_amd64.s:286 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc4201be000, 0xc61bff, 0xf, 0xc7f5a0, 0x741606)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4201be000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4201be000, 0xc42019dd78)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420147440, 0x110e010, 0x1, 0x1, 0x100070100000160)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42004df18, 0x2)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/containous/traefik/plugin/_test/_testmain.go:102 +0x1b2

goroutine 7 [syscall, 9 minutes]:
os/signal.signal_recv(0x93ae10)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 8 [chan receive, 9 minutes]:
github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Kill(0xc42015ca10)
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:391 +0xbe
github.com/containous/traefik/plugin.TestBasicPlugin(0xc4201be0f0)
	/go/src/github.com/containous/traefik/plugin/plugin_test.go:63 +0x8c9
testing.tRunner(0xc4201be0f0, 0xc7f5a0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 9 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f2614391f70, 0x72, 0x1)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420078a18, 0x72, 0xffffffffffffff01, 0x11207c0, 0x111b9b0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420078a18, 0xc4201d8001, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420078a00, 0xc4201d8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
os.(*File).read(0xc42000e0e8, 0xc4201d8000, 0x8000, 0x8000, 0xc420028660, 0x72984c, 0xc4200ce0c0)
	/usr/local/go/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc42000e0e8, 0xc4201d8000, 0x8000, 0x8000, 0x54, 0x0, 0x0)
	/usr/local/go/src/os/file.go:103 +0x6d
io.copyBuffer(0x111e180, 0xc42000e0c8, 0x111eb80, 0xc42000e0e8, 0xc4201d8000, 0x8000, 0x8000, 0xff, 0xc420028740, 0x71eaa6)
	/usr/local/go/src/io/io.go:392 +0x123
io.Copy(0x111e180, 0xc42000e0c8, 0x111eb80, 0xc42000e0e8, 0x54667d700000008, 0x5a05d2b9, 0xc420028798)
	/usr/local/go/src/io/io.go:362 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x7b6280, 0xc4201be0f0)
	/usr/local/go/src/os/exec/exec.go:264 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200c0f20, 0xc4201474c0)
	/usr/local/go/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:379 +0x646

goroutine 10 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f2614391df0, 0x72, 0x1)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420078ab8, 0x72, 0xffffffffffffff01, 0x11207c0, 0x111b9b0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420078ab8, 0xc4201d0001, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420078aa0, 0xc4201d0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
os.(*File).read(0xc42000e100, 0xc4201d0000, 0x8000, 0x8000, 0xc420028e60, 0x72984c, 0xc4200ce180)
	/usr/local/go/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc42000e100, 0xc4201d0000, 0x8000, 0x8000, 0x7c, 0x0, 0x0)
	/usr/local/go/src/os/file.go:103 +0x6d
io.copyBuffer(0x111e180, 0xc42000e0d8, 0x111eb80, 0xc42000e100, 0xc4201d0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:392 +0x123
io.Copy(0x111e180, 0xc42000e0d8, 0x111eb80, 0xc42000e100, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:264 +0x4d
os/exec.(*Cmd).Start.func1(0xc4200c0f20, 0xc420147520)
	/usr/local/go/src/os/exec/exec.go:380 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:379 +0x646

goroutine 11 [chan receive, 9 minutes]:
os/exec.(*Cmd).Wait(0xc4200c0f20, 0xc7ff28, 0xc42000e0c8)
	/usr/local/go/src/os/exec/exec.go:454 +0x135
github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start.func3(0xc42000e0d8, 0xc42000e0c8, 0xc4200c0f20, 0xc42015ca10, 0xc4200186c0)
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:529 +0x83
created by github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:522 +0xd26

goroutine 12 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc4200ce1c0, 0xc400000002)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4200ce1b0)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc4200ce180, 0xc4201e0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc42000e0d0, 0xc4201e0000, 0x1000, 0x1000, 0x81, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
bufio.(*Reader).fill(0xc420034f60)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc420034f60, 0xc42001e60a, 0xc420034d90, 0x7e791e, 0xc42000e020, 0xc420034d90, 0x6eb896)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc420034f60, 0xaa0c0a, 0xc42019e320, 0x2, 0xc4201a6060, 0x30, 0x0)
	/usr/local/go/src/bufio/bufio.go:416 +0x6b
bufio.(*Reader).ReadString(0xc420034f60, 0xc4201a600a, 0x30, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:456 +0x38
github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).logStderr(0xc42015ca10, 0x111e140, 0xc42000e0d0)
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:735 +0xab
created by github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:545 +0xd64

goroutine 13 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc4200ce100, 0xc400000001)
	/usr/local/go/src/runtime/sema.go:507 +0x110
sync.(*Cond).Wait(0xc4200ce0f0)
	/usr/local/go/src/sync/cond.go:56 +0x80
io.(*pipe).read(0xc4200ce0c0, 0xc4201f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:47 +0xc6
io.(*PipeReader).Read(0xc42000e0c0, 0xc4201f0000, 0x1000, 0x1000, 0x7f261444d558, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:130 +0x4c
bufio.(*Reader).fill(0xc4201f6f68)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc4201f6f68, 0xc4201f6e0a, 0x6c4a68, 0xc420018720, 0xc4200588a0, 0xc4201f6ef8, 0xc4201f6e58)
	/usr/local/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc4201f6f68, 0xc4201f6e0a, 0xc420018780, 0x54, 0x54, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:416 +0x6b
github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start.func4(0xc420018720, 0xc42000e0c0)
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:555 +0x16c
created by github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:550 +0xdaf

goroutine 15 [chan receive, 9 minutes]:
github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start.func5.1(0xc420018720)
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:570 +0x6d
created by github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin.(*Client).Start.func5
	/go/src/github.com/containous/traefik/vendor/github.com/hashicorp/go-plugin/client.go:569 +0x3f

rax    0xca
rbx    0x115dd80
rcx    0x71ee53
rdx    0x0
rdi    0x115de90
rsi    0x0
rbp    0x7ffdd24f96a0
rsp    0x7ffdd24f9658
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0x0
r14    0x71c6c0
r15    0x0
rip    0x71ee51
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```

**Comment by gotohr** [comment]
in that grpc example, there is this code:
```
	// We're a host. Start by launching the plugin process.
	client := plugin.NewClient(&plugin.ClientConfig{
		HandshakeConfig: shared.Handshake,
		Plugins:         PluginMap,
		Cmd:             exec.Command("sh", "-c", os.Getenv("KV_PLUGIN")),
```
if we swap that last line with
```
Cmd:             exec.Command(os.Getenv("KV_PLUGIN")),
```
thus removing sh wrapper, host kills subprocess and doesn't hang.
Now, can somebody tell me is this OK to do? Why do we wrap plugin cmd with sh?

**Comment by damianoneill** [comment]
@mitchellh first thanks for a fantastic project, I really appreciate your continued commitment to open source.

I have been trying to understand whether go-plugin is a good fit for a solution I'm working on.  I have looked through the code examples and watched your presentation on go-plugin.  Functionally it seems to give us exactly what we require.  

The only piece I'm struggling with is that we need to dockerize our services that will be using go-plugin, as they are running in a Kubernetes deployment.   

From this thread it seems that this is currently not possible, can you clarify if I have understood this correctly?  If that is the case is their a desire to support deployment in containers?

Thanks in advance, 
Damian.

**Comment by trung** [comment]
I am concerned about this issue but then when tested (following the steps in the original post) with the latest, i don't see this happen anymore.

```bash
$docker run --rm -it golang:latest
root@96ae5baaa7c4:/go# go version
go version go1.12.7 linux/amd64

$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 58
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: S5LS:YPZ6:3GWT:WNHN:IRX7:NSNL:E3F6:HWVT:GX53:LCV4:PXAB:5EW4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 53
 System Time: 2019-07-15T15:31:52.292492Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by mitchellh** [comment]
I'm unable to reproduce this anymore. It may be that the container, Go versions, who knows fixed this over the years. Thanks to everyone for submitting their reports.
